import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#%%
symbol = "ETHUSDT"
interval = "1d"    #денні свічки
limit = 500        # за останні 500 днів

url = f"https://data-api.binance.vision/api/v3/klines?symbol={symbol}&interval={interval}&limit={limit}"
response = requests.get(url)
data = response.json()

df = pd.DataFrame(data, columns=['timestamp', 'Open', 'High', 'Low', 'Close', 'Volume',
                                 'close_time', 'qav', 'num_trades', 'tbb', 'tbq', 'ignore']) #fields were generated by ai using api documentation
df = df[['timestamp', 'Open', 'High', 'Low', 'Close', 'Volume']].astype(float)
df['Date'] = pd.to_datetime(df['timestamp'], unit='ms')
df.set_index('Date', inplace=True)
print(df)
